allowBuilds:
  '@biomejs/biome': true
  '@infisical/cli': true
  esbuild: true
  workerd: true
minimumReleaseAge: 0
onlyBuiltDependencies:
  - esbuild
  - workerd
  - '@cloudflare/vite-plugin'
  - '@biomejs/biome'
  - '@infisical/cli'
