import { Hono } from 'hono';

/**
 * External HTTP boundary for my-web-2026.
 *
 * Hono handles **all traffic that is not generated by the TanStack Start UI**:
 *
 *   - `/api/*`          external API endpoints (when we want a stable contract
 *                        that is *not* tied to a server-function route)
 *   - `/webhooks/*`     inbound webhooks from external services
 *   - `/oauth/*`        OAuth callback handlers
 *   - `/integrations/*` third-party integration adapters
 *
 * Internal application operations invoked from the UI are TanStack Start
 * server functions (`createServerFileRoute` / `createServerFn`) and **must
 * not** be exposed through Hono. Both layers share domain/application code
 * under `src/domains/**`.
 *
 * This module is mounted into the Cloudflare Worker as a sub-application —
 * see `src/server.tsx` for the integration point.
 */
export const externalBoundary = new Hono<{ Bindings: Env }>();

externalBoundary.get('/api/v1/health', (c) =>
	c.json({
		status: 'ok',
		service: 'my-web-2026',
		layer: 'external-boundary',
		version: '0.1.0',
	}),
);

externalBoundary.notFound((c) => c.json({ error: 'not_found', path: c.req.path }, 404));

externalBoundary.onError((err, c) => {
	console.error('[boundary] unhandled', err);
	return c.json({ error: 'internal_error' }, 500);
});
