import { Hono } from 'hono';
import { accessCounterRouter } from './access-counter/router';
import { ApiKeyError } from './api-keys/middleware';
import { authRouter } from './auth/router';
import { requestIdMiddleware } from './middleware/request-id';

/**
 * External HTTP boundary for my-web-2026.
 *
 * Hono handles **all traffic that is not generated by the TanStack Start UI**:
 *
 *   - `/api/v1/*`       external REST API endpoints (stable contract
 *                        independent of any server-function route)
 *   - `/webhooks/*`     inbound webhooks from external services
 *   - `/oauth/*`        OAuth callback handlers
 *   - `/integrations/*` third-party integration adapters
 *
 * Internal application operations invoked from the UI are TanStack
 * Start server functions and **must not** be exposed through Hono.
 *
 * This module is mounted by the Worker entry at `src/server.ts`, which
 * dispatches based on path prefix before the request reaches TanStack
 * Start. Real Cloudflare `env` (with D1, R2, ASSETS, ...) flows in via
 * the `{ Bindings: Env }` type and Hono's `c.env` accessor.
 */
export const externalBoundary = new Hono<{ Bindings: Env }>();

// All `/api/v1/*` requests flow through the request-id middleware so
// error responses and worker logs share a common correlation token.
// New routers compose under the existing `/api/v1/*` prefixes; no
// change to `src/server.ts` is required.
externalBoundary.use('/api/v1/*', requestIdMiddleware);
externalBoundary.route('/', authRouter);
externalBoundary.route('/api/v1/access', accessCounterRouter);

externalBoundary.get('/api/v1/health', (c) =>
	c.json({
		status: 'ok',
		service: 'my-web-2026',
		layer: 'external-boundary',
		version: '0.1.0',
	}),
);

externalBoundary.get('/api/v1/db/ping', async (c) => {
	try {
		const row = await c.env.DB.prepare('SELECT 1 AS one').first<{ one: number }>();
		return c.json({ status: 'ok', binding: 'd1', one: row?.one ?? null });
	} catch (err) {
		console.error('[boundary] d1 ping failed', err);
		return c.json({ status: 'binding_error', binding: 'd1' }, 503);
	}
});

externalBoundary.get('/api/v1/media/ping', async (c) => {
	try {
		const object = await c.env.MEDIA.head('probe');
		if (object) {
			return c.json({ status: 'ok', binding: 'r2', key: 'probe' });
		}
		return c.json({ status: 'key_not_found', binding: 'r2' }, 404);
	} catch (err) {
		// R2 `head` throws a 404-shaped error when the key is missing;
		// we surface that as the canonical "bucket reachable" signal.
		const message = err instanceof Error ? err.message : String(err);
		if (/404|not[_ ]?found/i.test(message)) {
			return c.json({ status: 'key_not_found', binding: 'r2' }, 404);
		}
		console.error('[boundary] r2 ping failed', err);
		return c.json({ status: 'binding_error', binding: 'r2' }, 503);
	}
});

externalBoundary.notFound((c) => c.json({ error: 'not_found', path: c.req.path }, 404));

externalBoundary.onError((err, c) => {
	// `ApiKeyError` is thrown by `requireResourceAction` when an
	// authenticated key lacks the requested resource/action scope.
	// It carries the canonical status code + a stable error code;
	// the global onError surfaces it as the documented 403/401
	// instead of the generic 500 fallback. Without this mapping a
	// production caller missing a scope would see a 500 with no
	// information, while the test app (which has its own onError
	// to coerce these errors) would correctly see 403 — masking
	// the bug until it ships.
	if (err instanceof ApiKeyError) {
		return c.json({ error: err.code, status: err.status }, err.status);
	}
	console.error('[boundary] unhandled', err);
	return c.json({ error: 'internal_error' }, 500);
});
