import { createRouter as createTanStackRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen';

/**
 * TanStack Start router instance.
 *
 * The route tree is generated by `@tanstack/react-start` from `src/routes/**`.
 * Do not hand-edit `src/routeTree.gen.ts`.
 */
export function createRouter() {
	return createTanStackRouter({
		routeTree,
		scrollRestoration: true,
		defaultPreload: 'intent',
		context: {},
	});
}

declare module '@tanstack/react-router' {
	interface Register {
		router: ReturnType<typeof createRouter>;
	}
}
