/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminInvitationsRouteImport } from './routes/admin.invitations'
import { Route as AdminKeysRouteImport } from './routes/admin.keys'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInvitationsAcceptRouteImport } from './routes/admin.invitations.accept'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitationsAcceptRoute = AdminInvitationsAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => AdminInvitationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/invitations': typeof AdminInvitationsRouteWithChildren
  '/admin/keys': typeof AdminKeysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/invitations/accept': typeof AdminInvitationsAcceptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/invitations': typeof AdminInvitationsRouteWithChildren
  '/admin/keys': typeof AdminKeysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/invitations/accept': typeof AdminInvitationsAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/invitations': typeof AdminInvitationsRouteWithChildren
  '/admin/keys': typeof AdminKeysRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/invitations/accept': typeof AdminInvitationsAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/invitations'
    | '/admin/keys'
    | '/admin/login'
    | '/admin/invitations/accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/invitations'
    | '/admin/keys'
    | '/admin/login'
    | '/admin/invitations/accept'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/invitations'
    | '/admin/keys'
    | '/admin/login'
    | '/admin/invitations/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitations/accept': {
      id: '/admin/invitations/accept'
      path: '/accept'
      fullPath: '/admin/invitations/accept'
      preLoaderRoute: typeof AdminInvitationsAcceptRouteImport
      parentRoute: typeof AdminInvitationsRoute
    }
  }
}

interface AdminInvitationsRouteChildren {
  AdminInvitationsAcceptRoute: typeof AdminInvitationsAcceptRoute
}

const AdminInvitationsRouteChildren: AdminInvitationsRouteChildren = {
  AdminInvitationsAcceptRoute: AdminInvitationsAcceptRoute,
}

const AdminInvitationsRouteWithChildren =
  AdminInvitationsRoute._addFileChildren(AdminInvitationsRouteChildren)

interface AdminRouteChildren {
  AdminInvitationsRoute: typeof AdminInvitationsRouteWithChildren
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInvitationsRoute: AdminInvitationsRouteWithChildren,
  AdminKeysRoute: AdminKeysRoute,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
