// `handler` is the default TanStack Start Worker handler. The default
// export shape is `{ fetch(request) }` because `@tanstack/react-start`
// wraps `createStartHandler(defaultStreamHandler)` in a server-entry.
// Importing `@tanstack/react-start/server-entry` keeps the canonical
// CSRF middleware active; do NOT define a custom `startInstance` here.
// See ADR-0002 for the boundary policy.
import handler from '@tanstack/react-start/server-entry';
import { externalBoundary } from './http/hono';

/**
 * Path prefixes that must be served by the Hono external boundary
 * instead of the TanStack Start SSR pipeline.
 *
 *   /api/v1/*        external REST API
 *   /webhooks/*      inbound webhooks from external services
 *   /oauth/*         OAuth callback handlers
 *   /integrations/*  third-party integration adapters
 *
 * Internal application operations invoked from the UI use TanStack
 * Start server functions and never appear under these prefixes.
 *
 * Matching is exact-prefix-or-/ to avoid collisions like /api/v10 or
 * /api/v1evil accidentally entering the external boundary.
 */
const EXTERNAL_BOUNDARY_PREFIXES = ['/api/v1', '/webhooks', '/oauth', '/integrations'] as const;

function matchesExternalBoundary(pathname: string): boolean {
	return EXTERNAL_BOUNDARY_PREFIXES.some(
		(prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`),
	);
}

/**
 * Cache policy for Worker-generated HTML (Issue #291).
 *
 * `public/_headers` cannot own this: Cloudflare documents that
 * "Custom headers defined in the `_headers` file are not applied to
 * responses generated by your Worker code, even if the request URL
 * matches a rule." The `/` page is streamed by the TanStack Start SSR
 * handler, not served as a static asset, so its headers have to be set
 * here.
 *
 * Before this, the SSR response carried no `Cache-Control` at all. That
 * happened to behave acceptably only by accident — RFC 7234 §4.2.2
 * requires a `Last-Modified` for heuristic freshness, which SSR does not
 * emit, so browsers treated the page as stale-on-arrival anyway. The
 * policy is now explicit instead of implied:
 *
 *   `/admin*` -> `no-store`. Admin responses can carry invitation
 *                lists and key material; they must never land on disk
 *                in a browser HTTP cache. `no-store` also keeps Chrome
 *                from restoring them from the back/forward cache.
 *                Decided by path alone — see below.
 *   everything else -> `no-cache`. The page is dynamic (the hit counter
 *                and the reaction totals are rendered into the HTML on
 *                every request), so it must be revalidated before reuse.
 *                `no-cache` still allows the response to be stored and
 *                still permits bfcache, which a `no-store` would cost
 *                us on every back navigation.
 *
 * The admin decision is taken from the PATH ALONE, before any
 * content-type check. Gating `no-store` on `text/html` looked correct
 * but left a hole: anonymous `GET /admin` answers 307 → `/admin/login`
 * with no `content-type` at all, so the admin rule silently did not
 * apply to the one response most likely to be recorded in a cache
 * history. A redirect carries no body, so the harm was theoretical —
 * but the policy claimed "admin is no-store" and did not deliver it.
 * Now the path match alone decides `no-store` for every `/admin*`
 * response (HTML, redirect or otherwise).
 *
 * The `no-cache` branch for the rest of the site still requires
 * `text/html`: `/_serverFn/*` payloads and streamed data are not
 * documents and must not inherit a document cache policy.
 *
 * An existing `cache-control` is never overwritten, so anything the
 * framework already decided wins, and Hono never reaches this function
 * — the external boundary returns before it.
 */
function applyHtmlCachePolicy(request: Request, response: Response): Response {
	if (response.headers.has('cache-control')) return response;

	const { pathname } = new URL(request.url);
	// Exact-prefix-or-/ so `/administrator` cannot inherit the admin rule,
	// mirroring how `matchesExternalBoundary` guards `/api/v10`.
	const isAdmin = pathname === '/admin' || pathname.startsWith('/admin/');
	const value = isAdmin
		? 'no-store'
		: response.headers.get('content-type')?.includes('text/html')
			? 'no-cache'
			: null;
	if (value === null) return response;

	try {
		response.headers.set('cache-control', value);
	} catch {
		// Sealed headers (immutable guard) — leave the response as-is
		// rather than fail a page render over a cache hint.
		return response;
	}
	return response;
}

/**
 * Cloudflare Worker entry for my-web-2026.
 *
 * Default export shape matches the Cloudflare Workers `ExportedHandler`
 * contract. The `@cloudflare/vite-plugin` reads `wrangler.jsonc.main`,
 * resolves it through Vite, and uses the default export's `fetch`.
 *
 * Real `env` and `ctx` flow through to Hono so external-boundary
 * handlers can talk to D1, R2, KV, and other bindings without
 * indirection.
 */
export default {
	async fetch(request, env, ctx): Promise<Response> {
		const url = new URL(request.url);
		if (matchesExternalBoundary(url.pathname)) {
			return externalBoundary.fetch(request, env, ctx);
		}
		return applyHtmlCachePolicy(request, await handler.fetch(request));
	},
} satisfies ExportedHandler<Env>;
