/// <reference path="../../node_modules/@cloudflare/vitest-plugin/types/cloudflare-test.d.ts" />
import { SELF } from 'cloudflare:test';
import { describe, expect, it } from 'vitest';

/**
 * Worker HTML cache policy (Issue #291).
 *
 * `applyHtmlCachePolicy` in `src/server.ts` is the only place an
 * explicit `Cache-Control` can be attached to SSR HTML: Cloudflare
 * documents that `_headers` "are not applied to responses generated by
 * your Worker code", so `public/_headers` cannot cover `/`.
 *
 * These tests drive the real Worker through `SELF.fetch`, which is the
 * only layer that sees the actual response headers — a unit test on the
 * function would not catch a header that the runtime seals, nor a
 * content-type the SSR pipeline emits differently than expected.
 *
 * F2 regression: the first implementation gated the whole policy on
 * `content-type: text/html`. Anonymous `GET /admin` answers 307 →
 * `/admin/login` with no content-type at all, so the admin `no-store`
 * rule silently never applied to it while the PR claimed it did. The
 * policy now decides `no-store` from the path alone.
 */
async function fetchDocumentHeaders(
	path: string,
): Promise<{ status: number; cacheControl: string | null; contentType: string | null }> {
	const res = await SELF.fetch(`https://example.com${path}`, { redirect: 'manual' });
	return {
		status: res.status,
		cacheControl: res.headers.get('cache-control'),
		contentType: res.headers.get('content-type'),
	};
}

describe('Worker HTML cache policy (Issue #291)', () => {
	it('a dynamic non-admin page serves SSR HTML with no-cache', async () => {
		// `/contact` rather than `/`: the home route's loader needs the
		// `reactions` tables, and this file does not bootstrap them
		// (workerd cannot read `migrations/*.sql`, so each suite that
		// needs them inlines the SQL — see `test/integration/d1.test.ts`,
		// which already asserts `GET /` renders 200 once they exist).
		// The policy itself is decided per-path, not per-page, so a
		// loader-free 200 exercises exactly the same branch `/` takes.
		const { status, cacheControl, contentType } = await fetchDocumentHeaders('/contact');
		expect(status).toBe(200);
		expect(contentType).toContain('text/html');
		// Dynamic content must be revalidated before reuse.
		expect(cacheControl).toBe('no-cache');
	});

	it('GET /admin redirect carries no-store even with no content-type (F2)', async () => {
		const { status, cacheControl, contentType } = await fetchDocumentHeaders('/admin');
		// Anonymous /admin auth-gates to /admin/login — see
		// test/integration/admin-routing.test.ts.
		expect(status).toBeGreaterThanOrEqual(300);
		expect(status).toBeLessThan(400);
		// The redirect has no body and no content-type; the admin rule
		// must still land, because it is decided by path alone. This is
		// the exact combination the content-type guard used to drop.
		expect(contentType ?? '').not.toContain('text/html');
		expect(cacheControl).toBe('no-store');
	});

	it('GET /admin/login serves admin HTML with no-store', async () => {
		const { status, cacheControl, contentType } = await fetchDocumentHeaders('/admin/login');
		expect(status).toBe(200);
		expect(contentType).toContain('text/html');
		expect(cacheControl).toBe('no-store');
	});

	it('GET /admin/keys redirect carries no-store (protected child)', async () => {
		const { status, cacheControl } = await fetchDocumentHeaders('/admin/keys');
		expect(status).toBeGreaterThanOrEqual(300);
		expect(status).toBeLessThan(400);
		expect(cacheControl).toBe('no-store');
	});

	it('does not let a lookalike prefix inherit the admin rule', async () => {
		// Exact-prefix-or-/: `/administrator` must not become `no-store`
		// just because it starts with `/admin`.
		const { status, cacheControl, contentType } = await fetchDocumentHeaders('/administrator');
		expect(contentType).toContain('text/html');
		expect(cacheControl).toBe('no-cache');
		expect(status).toBe(404);
	});
});
